'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ankou/models/lamp-post/model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LampPost(props) {
  const { nodes, materials } = useGLTF('/nextjs-blog-deployment/models/ankou/models/lamp-post/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder096.geometry} material={materials['Black.012']} />
      <mesh geometry={nodes.Cylinder096_1.geometry} material={materials['Yellow.007']} />
    </group>
  )
}

useGLTF.preload('/nextjs-blog-deployment/models/ankou/models/lamp-post/model.gltf')
