'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ankou/models/rock/model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rock(props) {
  const { nodes, materials } = useGLTF('/nextjs-blog-deployment/models/ankou/models/rock/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.menhir_mini.geometry} material={materials['color_main.001']} />
    </group>
  )
}

useGLTF.preload('/nextjs-blog-deployment/models/ankou/models/rock/model.gltf')
