'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ankou/models/tree-spruce/model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TreeSpruce(props) {
  const { nodes, materials } = useGLTF('/nextjs-blog-deployment/models/ankou/models/tree-spruce/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tree-spruce'].geometry} material={materials.color_main} />
    </group>
  )
}

useGLTF.preload('/nextjs-blog-deployment/models/ankou/models/tree-spruce/model.gltf')
